CREATE TABLE `Order` (
    id              INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    orderNumber     VARCHAR(100),
    customer_id     INT         NULL,
    orderDate       DATETIME,
    status          VARCHAR(50) NOT NULL DEFAULT 'NEW',
    totalPrice      DECIMAL(19, 2),
    shippingPrice   DECIMAL(19, 2),
    paymentPrice    DECIMAL(19, 2),
    paymentMethod_id  INT NULL,
    shippingMethod_id INT NULL,
    customerNote    TEXT,
    adminNote       TEXT,
    billingName     VARCHAR(255),
    billingStreet   VARCHAR(255),
    billingCity     VARCHAR(255),
    billingZip      VARCHAR(50),
    billingCountry  VARCHAR(100),
    deliveryName    VARCHAR(255),
    deliveryStreet  VARCHAR(255),
    deliveryCity    VARCHAR(255),
    deliveryZip     VARCHAR(50),
    deliveryCountry VARCHAR(100),
    isPaid          BOOLEAN     NOT NULL DEFAULT FALSE,
    guestEmail      VARCHAR(255),
    guestPhone      VARCHAR(50),
    token           VARCHAR(36) NOT NULL DEFAULT '',
    url             VARCHAR(255),
    published       BOOLEAN     NOT NULL DEFAULT TRUE,
    FOREIGN KEY (customer_id) REFERENCES JakonUser (id),
    FOREIGN KEY (paymentMethod_id) REFERENCES PaymentMethod (id),
    FOREIGN KEY (shippingMethod_id) REFERENCES ShippingMethod (id)
);
